---
- name: Create AWS infrastructure
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - "region/{{ env }}_vars.yml"

  roles:
    - ec2-base
    - ec2-sg
    - get_ami
    - start_servers