- name: Set Hostname
  hosts: tag_Type_dokkudb
  user: ubuntu
  gather_facts: false

  roles:
    - set-hostname

- name: Install and Configure Dokku
  hosts: tag_Type_dokkudb
  user: ubuntu
  gather_facts: false

  roles:
    - dokku

- name: Configure Mongo 
  hosts: tag_Type_dokkudb
  user: ubuntu
  gather_facts: false

  roles:
    - dokku-mongo
