- name: Install and Configure Dokku
  hosts: tag_Type_dokkudb
  user: ubuntu
  gather_facts: false

  roles:
    - dokku

- name: Add key to Dokku
  hosts: tag_Type_dokkudb
  connection: local
  user: root
  gather_facts: false

  roles:
    - dokku_key
