- name: Display all variables/facts known for a host
  gather_facts: true
  tasks: 
    - debug: var=hostvars[inventory_hostname]
  hosts: tag_Type_dokkudb

- name: Set Hostname
  hosts: tag_Type_dokkudb
  user: ubuntu
  gather_facts: false

  roles:
    - set-hostname

- name: Mount and connect to EFS
  hosts: tag_Type_dokkudb
  sudo: true 
  gather_facts: true
  vars:

    efsFolderList:
      - {folderPath: "/var/lib/dokku", folderOwner: "root", folderGroup: "root", folderMode: "0644" , fileSystemId: "{{ec2_tag_EfsId}}"} 
    awsRegion: "{{ec2_region}}"
    mountState: mounted

  roles:
    - fdfk.efsAwsMount

- name: Install and Configure Dokku 
  hosts: tag_Type_dokkudb
  user: ubuntu
  gather_facts: false

  roles:
    - dokku

- name: Configure Mongo 
  hosts: tag_Type_dokkudb
  user: ubuntu
  gather_facts: false

  roles:
    - dokku-mongo

- name: Configure Route 53
  hosts: tag_Type_dokkudb

  roles: 
    - configure-route53