#
# This playbook provisions and configures a Dokku server.
#
- name: Provision EC2
  hosts: local
  connection: local
  user: root

  roles:
    - ec2

- name: Install and Configure Dokku
  hosts: ec2hosts
  user: ubuntu
  gather_facts: false

  roles:
    - dokku

- name: Install and configure dokku-mongo
  hosts: ec2hosts
  user: ubuntu
  gather_facts: false

  roles:
    - dokku-mongo

- name: Add key to Dokku
  hosts: ec2hosts
  connection: local
  user: root
  gather_facts: false

  roles:
    - dokku_key
