---
# Install Dokku

- name: Update dependencies
  command: "sudo apt-get update"

- name: Install Dokku
  shell: "wget -qO - https://raw.github.com/progrium/dokku/v0.2.0/bootstrap.sh | sudo DOKKU_TAG=v0.2.0 bash"
  sudo: true
  async: 1200

- name: Add VHOST file
  shell: echo {{domain}} > /home/dokku/VHOST
  sudo: true