---
# Install Dokku

- name: Update dependencies
  command: "sudo apt-get update"

# https://gist.github.com/rothgar/8793800
# Idempotent way to build a /etc/hosts file with Ansible using your Ansible hosts inventory for a source.
# Will include all hosts the playbook is run on.
# Inspired from http://xmeblog.blogspot.com/2013/06/ansible-dynamicaly-update-etchosts.html

- name: "Build hosts file"
  lineinfile: dest=/etc/hosts regexp='.*{{ tag_Host }}$' line="127.0.0.1 {{tag_Host}}.{{domain}}" state=present
  when: tag_Host is defined

- name: Install Dokku
  shell: "wget -qO - https://raw.github.com/progrium/dokku/v0.7.0/bootstrap.sh | sudo DOKKU_TAG=v0.7.0 bash"
  sudo: true

- name: Add VHOST file
  shell: echo {{domain}} > /home/dokku/VHOST
  sudo: true