---
# Install Mongo

- name: Install Mongo plugin
  command: dokku plugin:install https://github.com/dokku/dokku-mongo.git mongo
  ignore_errors: yes
  sudo: true

- name: Clone Mongo database
  command: dokku mongo:clone {{app_name}} {{app_name}}_backup
  ignore_errors: yes
  sudo: true
  environment:
    MONGO_CONFIG_OPTIONS: '{{mongo_options}}'

- name: Destroy original db
  command: dokku mongo:destroy {{app_name}}  --force
  ignore_errors: yes
  sudo: true
  
- name: Clone backup db to orignal
  command: dokku mongo:clone {{app_name}}_backup {{app_name}}
  ignore_errors: yes
  sudo: true
  environment:
    MONGO_CONFIG_OPTIONS: '{{mongo_options}}'

- name: Destroy backup
  command: dokku mongo:destroy {{app_name}}_backup --force
  ignore_errors: yes
  sudo: true
  
- name: Create Mongo database for the app if it still doesn't exist (fresh install)
  command: dokku mongo:create {{app_name}}
  ignore_errors: yes
  environment:
    MONGO_CONFIG_OPTIONS: '{{mongo_options}}'

- name: Expose the mongo 
  command: dokku mongo:expose {{app_name}}
  ignore_errors: yes
  environment:
    MONGO_CONFIG_OPTIONS: '{{mongo_options}}'