---
# Install Postgres

- name: Install Mongo plugin
  command: dokku plugin:install https://github.com/dokku/dokku-mongo.git mongo
  async: 1200
  sudo: true

- name: Create Postgres database for the app
  command: sudo dokku postgresql:create {{app_name}}
  ignore_errors: yes