
# https://gist.github.com/rothgar/8793800
# Idempotent way to build a /etc/hosts file with Ansible using your Ansible hosts inventory for a source.
# Will include all hosts the playbook is run on.
# Inspired from http://xmeblog.blogspot.com/2013/06/ansible-dynamicaly-update-etchosts.html

- name: "Build /etc/hosts file"
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost {{ec2_tag_Name}}.{{domain}}' owner=root group=root mode=0644
  when: ec2_tag_Name is defined
  sudo: true

- name: "Set hostname"
  lineinfile: dest=/etc/hostname regexp='.*' line='{{ec2_tag_Name}}.{{domain}}' owner=root group=root mode=0644
  when: ec2_tag_Name is defined
  sudo: true

- name: "Restart hostname service"
  shell: "service hostname restart"
  when: ec2_tag_Name is defined
  sudo: true